services:
  postgres:
    image: postgres:16
    restart: always
    container_name: n8n_postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - sonarQube_network
  
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${POSTGRES_NON_ROOT_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_NON_ROOT_PASSWORD}

    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "4G"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    ports:
      - "81:9000"
    depends_on:
      - postgres
    networks:
      - sonarQube_network

volumes:
  sonarqube_data:
  postgresql_data:

networks:
  sonarQube_network: