services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST

    restart: unless-stopped
    networks:
      - ollama_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_API_BASE_URL}
    restart: unless-stopped
    networks:
      - ollama_network
    depends_on:
      - ollama

#  ollama-webui: 
#    image: ghcr.io/ollama-webui/ollama-webui:main
#    container_name: ollama-ui
#    ports:
#      - "3000:8080"
#    volumes:
#      - ollama_webui_data:/app/backend/data
#    environment:
#      - OLLAMA_API_BASE_URL
#    depends_on:
#      - ollama
#    restart: unless-stopped
#    networks:
#      - ollama_network 

volumes:
  ollama_data:
    name: ollama_data
  ollama_webui_data:
    name: ollama_webui_data
  open_webui_data:
    name: open_webui_data
networks:
  ollama_network:
    name: ollama_network